#!/usr/bin/env python3
"""
Process a trade impact CSV into a Chart.js Sankey data file.

Usage:
  python scripts/process_trade_impact.py \
    --csv year/2022/WM/domestic/trade_impact.csv \
    --from-col Exporter --to-col User --indicator impact_value \
    --top-n 20 \
    --out bea-dashboard/trade_sankey_data.js

The script is intentionally flexible: if you don't know column names, it will try
to infer a numeric indicator column and will print available numeric columns.
You can pass --from-col and --to-col to specify which columns represent the
source and target nodes for the Sankey. If omitted, the script will try a few
common names.
"""
import argparse
import json
import sys
from pathlib import Path

import pandas as pd


COMMON_FROM = ["source", "from", "exporter", "origin", "sector", "industry"]
COMMON_TO = ["target", "to", "user", "destination", "flow", "sector", "industry"]


def infer_column(cols, candidates):
    for c in candidates:
        if c in cols:
            return c
    # try lowercase match
    lower = {x.lower(): x for x in cols}
    for c in candidates:
        if c.lower() in lower:
            return lower[c.lower()]
    return None


def list_numeric_columns(df):
    numerics = df.select_dtypes(include=["number"]).columns.tolist()
    # also detect numeric-like strings
    for col in df.columns:
        if col in numerics:
            continue
        try:
            pd.to_numeric(df[col].dropna())
            numerics.append(col)
        except Exception:
            pass
    return numerics


def build_sankey(df, from_col, to_col, indicator_col, top_n=20):
    df = df.copy()
    df[indicator_col] = pd.to_numeric(df[indicator_col], errors="coerce").fillna(0)

    # aggregate
    grp = df.groupby([from_col, to_col], dropna=False)[indicator_col].sum().reset_index()

    # compute top targets (users)
    target_totals = grp.groupby(to_col)[indicator_col].sum().reset_index()
    target_totals = target_totals.sort_values(by=indicator_col, ascending=False)
    top_targets = target_totals[to_col].head(top_n).tolist()

    # mark others
    grp["_target"] = grp[to_col].where(grp[to_col].isin(top_targets), "Other")

    # re-aggregate with Other
    agg = grp.groupby([from_col, "_target"], dropna=False)[indicator_col].sum().reset_index()

    # create nodes list
    from_nodes = agg[from_col].astype(str).unique().tolist()
    to_nodes = agg["_target"].astype(str).unique().tolist()

    # ensure deterministic ordering
    nodes = sorted(set(from_nodes + to_nodes))
    node_index = {n: i for i, n in enumerate(nodes)}

    links = []
    for _, row in agg.iterrows():
        src = str(row[from_col])
        tgt = str(row["_target"])
        val = float(row[indicator_col])
        if val == 0:
            continue
        links.append({
            "source": src,
            "target": tgt,
            "value": val,
        })

    # Chart.js sankey expects nodes with id/label and links referencing ids (here we'll use ids as labels)
    nodes_out = [{"id": n, "label": n} for n in nodes]

    return {"nodes": nodes_out, "links": links}


def write_js(output_path: Path, sankey_obj: dict, metadata: dict):
    # Write a JS file that defines window.sankeyData and window.sankeyMeta
    content = []
    content.append("/* Generated by scripts/process_trade_impact.py */")
    content.append("window.sankeyData = "+json.dumps(sankey_obj, indent=2)+";")
    content.append("window.sankeyMeta = "+json.dumps(metadata, indent=2)+";")
    output_path.write_text("\n".join(content), encoding="utf-8")
    print(f"Wrote {output_path}")


def main(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("--csv", required=True, help="Path to CSV input")
    p.add_argument("--from-col", default=None, help="Column name for source nodes")
    p.add_argument("--to-col", default=None, help="Column name for target/user nodes")
    p.add_argument("--indicator", default=None, help="Numeric column to use as indicator (impact) ")
    p.add_argument("--top-n", type=int, default=20, help="Top N target users to show (others aggregated)")
    p.add_argument("--out", default="bea-dashboard/trade_sankey_data.js", help="Output JS file path")

    args = p.parse_args(argv)

    csv_path = Path(args.csv)
    if not csv_path.exists():
        print(f"CSV file not found: {csv_path}")
        sys.exit(2)

    df = pd.read_csv(csv_path)
    cols = df.columns.tolist()
    print("Detected columns:", cols)

    from_col = args.from_col or infer_column(cols, COMMON_FROM)
    to_col = args.to_col or infer_column(cols, COMMON_TO)

    numeric_cols = list_numeric_columns(df)
    print("Numeric columns detected:", numeric_cols)

    indicator_col = args.indicator
    if not indicator_col:
        if len(numeric_cols) == 1:
            indicator_col = numeric_cols[0]
            print(f"Only one numeric column found; using {indicator_col} as indicator")
        else:
            # try common names
            for cand in ["impact", "value", "amount", "impact_value", "trade_value", "impact_sum"]:
                if cand in cols or cand in numeric_cols:
                    indicator_col = cand
                    print(f"Auto-selected indicator column: {indicator_col}")
                    break

    if indicator_col not in df.columns:
        print("Indicator column not found. Provide --indicator with one of:", numeric_cols)
        sys.exit(2)

    if from_col is None or to_col is None:
        print("Could not infer from/to columns. Provide --from-col and --to-col. Candidates were:")
        print("from candidates:", COMMON_FROM)
        print("to candidates:", COMMON_TO)
        sys.exit(2)

    sankey = build_sankey(df, from_col, to_col, indicator_col, top_n=args.top_n)

    metadata = {
        "csv": str(csv_path),
        "from_col": from_col,
        "to_col": to_col,
        "indicator": indicator_col,
        "top_n": args.top_n,
        "available_numeric_columns": numeric_cols,
    }

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    write_js(out_path, sankey, metadata)


if __name__ == "__main__":
    main()
